### 넷플릭스 영화 추천 시스템

In [21]:
import pandas as pd 
import numpy as np

movies=pd.read_csv("movies.csv")  # movie_id, title, genres
ratings=pd.read_csv("ratings.csv")  # user_id, movie_id, ratings

In [22]:
# 필요 데이터들만 병합
data=pd.merge(ratings, movies, on="movieId")
column=['userId','movieId','rating','title','genres']
data=data[column]
data
 
movie_rating=data.pivot_table(index="title",  columns='userId')['rating']
movie_rating.head()

userId,1,2,3,4,5,6,7,8,9,10,...,7111,7112,7113,7114,7115,7116,7117,7118,7119,7120
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$5 a Day (2008),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Neath the Arizona Skies (1934),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# NaN은 -1값으로 변경
movie_rating.fillna(0, inplace=True)
movie_rating

userId,1,2,3,4,5,6,7,8,9,10,...,7111,7112,7113,7114,7115,7116,7117,7118,7119,7120
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$5 a Day (2008),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Neath the Arizona Skies (1934),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
¡Three Amigos! (1986),0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nos amours (1983),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
movie_rating.shape

(14021, 7120)

### 유사도 기반 추천 시스템

**추천 시스템은 content-base와 collaborative filtering으로 나눌 수 있다.**
- content-base : 추천하고자 하는 아이템에 대한 정보를 기반으로 추천하는 알고리즘. (예: 특정 배우, 장르)
- collaborative filtering : 사용자 간 유사도에 중점을 둔 추천 시스템, 사용자의 행동 패턴에 따라 추천이 가능함.

**collaborative filtering**
- item-based CF : 상품 간 유사도를 기반으로 추천
- user-based CF : 유저 간 유사도를 기반으로 상품을 추천
- matrix factorization CF : 행렬 기반 추천 시스템

#### 피어슨 상관계수 : matrix factorization / SVD(특이값 분해)
- 두 변수 X 와 Y 간의 선형 상관 관계를 계량화한 수치로서  -1 ~ 1 사이의 값을 가진다.
- +1은 완벽한 양의 선형 상관 관계, 0은 선형 상관 관계 없음, -1은 완벽한 음의 선형 상관 관계를 의미한다.
- 일반적으로 상관관계는 피어슨 상관관계를 의미하는 상관계수이다.
- 상관계수 = 공분산 / (표준편차 * 표준편차)

In [ ]:
from sklearn.decomposition import TruncatedSVD

syd = TruncatedSVD(n_components = 12)  # latent 값 12
matrix = syd.fit_transform(movie_rating)
matrix.shape

In [ ]:
# 피어슨 상관계수 구하기
corr = np.corrcoef(matrix)
corr.shape

In [ ]:
# heatmap 그리기
import matplotlib.pyplot as plt
import seaborn as sns

ax = sns.heatmap(movie_rating)

In [ ]:
movie_title = movie_rating.columns
title_list = list(movie_title)
coffey = title_list.index('Toy Story (1995)')

In [ ]:
corr_coffey = corr[coffey]
list(movie_title[(corr_coffey >= 0.9)])[:10]

#### 코사인 유사도 : item based CF
- 각도 기반의 계산법으로 벡터의 크기에 영향을 받지 않는다.
- 값의 범위는 -1 ~ 1이며 1에 가까울수록 유사하다고 판단한다.

In [26]:
# item_based (pip install sklearn)
from sklearn.metrics.pairwise import cosine_similarity

item_based = cosine_similarity(movie_rating)
item_based = pd.DataFrame(data = item_based, index = movie_rating.index, columns = movie_rating.index)
item_based.head()

title,"""Great Performances"" Cats (1998)",$5 a Day (2008),'71 (2014),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'R Xmas (2001),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nos amours (1983),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",1.000000,0.209925,0.0,0.174598,0.315244,0.445823,0.218320,0.179530,0.094086,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
$5 a Day (2008),0.209925,1.000000,0.0,0.184407,0.332956,0.470871,0.230586,0.189617,0.099372,0.054516,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
'71 (2014),0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.102508,0.0,0.0,0.066979,0.0,0.0,0.0,0.000000,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.174598,0.184407,0.0,1.000000,0.276924,0.391630,0.191782,0.157707,0.082649,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.026485,0.0,0.0
'Neath the Arizona Skies (1934),0.315244,0.332956,0.0,0.276924,1.000000,0.707107,0.346272,0.284747,0.149227,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0

In [27]:
# 1에 가까운 유사도 찾기
def recommend(title):
    # 제목과 유사한 영화 상위 5개 추천
    return item_based[title].sort_values(ascending=False)[:6]

In [28]:
recommend('Toy Story (1995)')

title
Toy Story (1995)                                     1.000000
Star Wars: Episode IV - A New Hope (1977)            0.579630
Independence Day (a.k.a. ID4) (1996)                 0.573522
Star Wars: Episode VI - Return of the Jedi (1983)    0.552696
Forrest Gump (1994)                                  0.543101
Mission: Impossible (1996)                           0.542263
Name: Toy Story (1995), dtype: float64